[project]
name = "tiny-grpo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "accelerate==1.3.0",
    "torch==2.5.1",
    "transformers==4.48.1",
    "wandb==0.19.4",
]
